<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for timestamp_converter_timestamp_form.
 */
function timestamp_converter_form_timestamp_converter_timestamp_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Add any alterations to the form here.
}

/**
 * Form submission handler for the timestamp_converter_timestamp_form form.
 */
function timestamp_converter_form_timestamp_converter_timestamp_form_submit(array &$form, FormStateInterface $form_state) {
  $input_timestamp = $form_state->getValue('timestamp');

  if (is_numeric($input_timestamp)) {
    $originalDateTime = new DateTime("@$input_timestamp", new DateTimeZone("UTC"));
    $originalDateTime->setTimezone(new DateTimeZone("America/New_York"));
    $originalDate = $originalDateTime->format('n-d-Y H:i:s A');

    $modifiedDateTime = new DateTime("@$input_timestamp", new DateTimeZone("UTC"));
    $modifiedDateTime->setTimezone(new DateTimeZone("America/New_York"));
    $modifiedDateTime->modify('+12 hours');
    $convertedTime = $modifiedDateTime->format('n-d-Y H:i:s ');

    
    // Use the messenger service to display messages.
    \Drupal::messenger()->addMessage(t("Original Timestamp: $originalDate\nConverted Time: $convertedTime"));
     $form_state->setValue('convertedTime', $convertedTime);
  } else {
    // Use the messenger service for error messages.
    \Drupal::messenger()->addError(t('Invalid timestamp. Please enter a numeric value.'));
  }
}


  