<?php

/**
 * Implements hook_theme().
 */
function custom_module_theme() {
  return [
    'hello_block' => [
      'variables' => ['data' => [], ],
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function custom_hotels_theme($existing, $type, $theme, $path) {
  return [
    'demotemplates' => [
      'variables' => [
        'data' => NULL,
       ],
      'template' => 'test_demo',
    ],
  ];
}
